- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

#- name: Apply Identity Server configuration to is nodes
  #hosts:
#   - is_1
  #become: yes   
#  roles:
#    - is
