---
- name: Install and Configure WSO2 Identity Server
  hosts: is
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:
    - name: Set installation directory information
      set_fact:
        product_dir: "{{ target }}/is"
        carbon_home: "{{ target }}/is/{{ product_name }}-{{ product_version }}"

    - name: Create product directory
      file:
        path: "{{ product_dir }}"
        state: directory
        mode: 0755

    - name: Copy WSO2IS service file
      template:
        src: "wso2is.service.j2"
        dest: /etc/systemd/system/wso2is.service

    - name: Stop wso2is as a service
      systemd:
        name: wso2is
        state: stopped

    - name: Remove existing setup
      file:
        path: "{{ carbon_home }}"
        state: absent

    - name: Unzip WSO2 Identity Server Package
      unarchive:
        src: "{{ 'local' if pack_location == 'local' else remote_pack }}"
        dest: "{{ product_dir }}"
        mode: u=rw,g=r,o=r
        remote_src: yes
      when: pack_location == "local" or pack_location == "remote"

    - name: Copy configuration templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ config_files }}"

    # You can enable customization by uncommenting the following line
    # - import_tasks: custom.yml

    - name: Change the owner of WSO2 directory
      file:
        path: "{{ target }}"
        state: directory
        recurse: yes
        owner: "{{ wso2_user }}"
        group: "{{ wso2_group }}"
        mode: 0755

- name: Start WSO2 Identity Server as a service
  hosts: is
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Start wso2-is as a service
      systemd:
        name: wso2is
        state: started
        daemon_reload: yes
