---
  - block:
    - name: Create group
      group: name=wso2 state=present gid=802

    - name: Add wso2carbon user
      user: name="{{ wso2_user }}" shell=/bin/bash group=wso2 state=present uid=802

    - name: System performance tuning
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ performance_tuning_file_list }}"
      when: enable_performance_tuning

    - name: Create Java directory
      file:
        path: "{{ java_home }}"
        state: directory

    - name: Unarchive JDK distribution from local source
      unarchive:
        src: "{{ product_package_location }}/lib/{{ jdk_name }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
      when: pack_location == "local"

    - name: Unarchive JDK distribution from remote source
      unarchive:
        src: "{{ remote_jdk }}"
        dest: "{{ java_home}}"
        extra_opts: [--strip-components=1]
        remote_src: yes
      when: pack_location == "remote"

    - name: Create Java symbolic link
      file:
        src: "{{ java_home }}"
        dest: "{{ java_symlink }}"
        state: link

    - name: Install unzip package
      package:
        name: unzip
        state: present

    - name: Add OpenJDK 8 repository
      become: yes
      become_user: root
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present


    - name: Install Java 8
      become: yes
      become_user: root
      apt:
        name: openjdk-8-jdk 
        state: present
      #when: pack_location == "local"  
    

    become: true
    become_user: root
